name: Go
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: |
        mkdir -p ./build/
        go build -o ./build/ -v ./multinet/...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ./build/
