name: Go
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"

      - name: Build
        run: |
          mkdir -p ./build/
          GOOS=windows GOARCH=amd64 go build -o ./build/multinet-windows-amd64.exe -v ./multinet/...
          GOOS=linux GOARCH=amd64 go build -o ./build/multinet-linux-amd64 -v ./multinet/...
          GOOS=darwin GOARCH=amd64 go build -o ./build/multinet-darwin-amd64 -v ./multinet/...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/
